---
- hosts: database
  handlers:
    - name: restart mysql
      service:
        name: mysql
        state: restarted
      become: yes
  tasks:
    - name: 'Instala pacotes de dependencia do sistema operacional'
      apt:
        update_cache: yes
        cache_valid_time: 3600 #1 hora
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
        - mysql-server-5.6
        - python-mysqldb

    - name: 'Cria o banco no MySQL'
      mysql_db:
        name: ansible_db
        login_user: root
        state: present

    - name: 'Cria usuario no MySQL'
      mysql_user:
        login_user: root
        name: ansible_user
        password: 12345
        priv: 'ansible_db.*:ALL'
        state: present
        host: '{{ item }}'
      with_items:
        - 'localhost'
        - '127.0.0.1'
        - '192.17.177.60'
        - '192.17.177.1'
